"""输入:沃尔玛下架原因串 / feed 报错四元组 → 输出:16 码归类 + 政策名(纯函数)。

方案定稿 `docs/error_taxonomy.md`(2026-09-01,所有者认可的码表/判据/优先序)。
判据串一律取自 2026-08-31 生产全量实查原文,**禁止拟写**;机器可验形式是两份
语料夹具 `tests/fixtures/reason_corpus.jsonl` / `feed_error_corpus.jsonl` ——
**引擎迁就语料,不是语料迁就引擎**。

第一步只做「解析→归类」,不接处置:本模块的唯一消费者是对照报告工作流
`workflows/error_reclass_report.py`;生产归类路径仍是
`services/problem_products.categorize()`(A-L 单字母码),换轨在第二步,
门 = 所有者过完对照报告。**这不是双轨**,是 NRTL 先例的"先补后删"。

纯函数纪律(方案 §四):不 import db/api/workflows,不读环境变量,零副作用;
政策表字典由调用方注入。码表与主码序从 `registry.resources` 取(铁律 3)。

公开面:`split_reasons / normalize_atom / extract_policy / classify_atom /
classify_reasons / classify_feed_error / RULES`;另有报告侧消费的
`policy_join`(只做政策表 join,不参与判定;2026-09-03 C 批随改名落地删掉了
它背后的旧名别名表 —— 词形对不上就是缺口,不做语义合并)。
"""

from __future__ import annotations

import html
import re
from typing import Iterable, NamedTuple

from registry import resources
# ⚠ 政策名归一化只有一份实现(`services/policy_names`);这里 import 的是**那一份**,
#   不是抄一份进来 —— 两份归一化各自漂移不会报错,只会让同一个名字在报告侧与
#   同步侧对到不同的行(见 `_norm_key`)。`policy_join` 的形参恰好也叫
#   policy_names,故只引入函数本身,不引入模块名,免得同名两义。
from services.policy_names import norm_category

# 主码序 → 名次(记录级取"名次最小"的原子码,方案 §3.5)
_SEVERITY_RANK = {code: i
                  for i, code in enumerate(resources.ERROR_CATEGORY_SEVERITY)}

# AI 内容审查的尾句锚(方案 §3.3 序 0;也是 split_reasons 的不拆闸)。
# 沃尔玛这段文案自身含分号,按 "; " 拆会把一句话劈成两条假原子。
_AI_TAIL = "generated by ai"


# ══════════════════════════════════════════════════════════════════════════════
#  一、规范化(方案 §3.2)
# ══════════════════════════════════════════════════════════════════════════════

_UNESCAPE_ROUNDS = 3            # &amp;amp; 双重转义:循环到不动点,≤3 次
_TAG_RE = re.compile(r"<[^>]{1,80}>")
# 链接标记 ||链文本@@@url||:保留链文本、丢 url。
# 分隔符写 @{2,} 而不是死的 @@@ —— 生产实见 `||Listing Quality Dashboard@@https…||`
# 只有两个 @(语料 reason#54),死写三个会把整条 url 留在正文里。
_LINK_RE = re.compile(r"\|\|([^|]*?)@{2,}[^|]*?\|\|")
# 残缺标记(无闭合 ||,语料 reason#10/#12/#28 的 `- )` 结尾那批):url 段只吃
# **一个非空白 token**,不吃到行尾 —— 吃到行尾会把标记后面的整句话一起吞掉
# (多原子记录里那可能正是 PROHIBITED_FINAL 那一句)。剥不净不报错(方案 §3.2.3)。
_LINK_BROKEN_RE = re.compile(r"\|\|([^|@]*)@{2,}\S*")


class Norm(NamedTuple):
    """规范化后的两个副本:text=原大小写(供政策名抽取),fold=casefold(供句式匹配)。"""

    text: str
    fold: str


def normalize_atom(text: str | None) -> Norm:
    """输入:一条原子原文 → 输出:Norm(原大小写副本, casefold 副本)。

    顺序照方案 §3.2:转义还原 → 剥 HTML 标签 → 剥链接标记 → 折叠空白。
    ⚠ 标签替成**空格**再折叠空白(方案原文写"→空"):生产实见
    `…Unpublished Items</p><p>&nbsp;page.</p>`,替空串会把 `Items` 与 `page`
    粘成一个词,而本引擎全靠子串匹配。折叠空白(第 4 步)会把多余空格收掉,
    两种写法在语料上输出一致。幂等:对已规范化的串再跑一次结果不变。
    """
    s = text or ""
    for _ in range(_UNESCAPE_ROUNDS):
        u = html.unescape(s)
        if u == s:
            break
        s = u
    s = _TAG_RE.sub(" ", s)
    s = _LINK_RE.sub(r"\1", s)
    s = _LINK_BROKEN_RE.sub(r"\1", s)
    s = s.replace("||", " ")            # 落单的裸标记:去掉,不粘词
    s = " ".join(s.split())             # \xa0(&nbsp;)也算空白,一并折叠
    return Norm(s, s.casefold())


def split_reasons(text: str | None) -> list[str]:
    """输入:库里的下架原因串 → 输出:原子列表(按 "; " 拆)。

    api/items.py 用 `"; ".join(reasons)` 落库,故拆分符是 "; "。
    ⚠ **整行含 AI 尾句时不拆**(方案 §3.1):那段文案自身带分号。
    拆分安全性已生产实证:最短原子 36 字符是完整句。
    """
    raw = (text or "").strip()
    if not raw:
        return []
    if _AI_TAIL in normalize_atom(raw).fold:
        return [raw]
    return [p.strip() for p in raw.split("; ") if p.strip()]


# ══════════════════════════════════════════════════════════════════════════════
#  二、判据表(方案 §3.3;表序即优先级,首命中即码)
# ══════════════════════════════════════════════════════════════════════════════
#
# 判据纪律(方案 §3.3 尾注):**不锚句首、不依赖 "This"** —— 生产有 29 条缺
# 首字母的 `his item…` typo,锚句首会整批漏判。全部 casefold 子串/正则。


class Rule(NamedTuple):
    """一条判据:order=表序(即优先级),code=16 码之一,needles/pattern/all_of 三选一或并存。"""

    order: int
    code: str
    label: str                      # 人话说明(报告与守门测试打印用)
    needles: tuple[str, ...] = ()   # 任一子串命中即算
    pattern: re.Pattern | None = None   # 补充正则(在 casefold 副本上跑)
    all_of: tuple[str, ...] = ()    # 必须**同时**含(POLICY 用)
    via_ai: bool = False            # 命中即标 AI 生成
    catch_all: bool = False         # 兜底(恒真)


RULES: tuple[Rule, ...] = (
    # 序 0:AI 内容审查。整原子短路,正文不再进任何规则。
    Rule(0, "CONTENT", "AI 生成的内容审查文案", ("generated by ai",), via_ai=True),
    # 序 1:升格码。通用政策拒 + "把 product type 选对" = 病根在我方类目判定,
    # 不是商品违禁 —— 压过 POLICY(生产 2,957 条)。
    Rule(1, "PT_WRONG", "沃尔玛明示改 product type",
         ("appropriate product type selected",)),
    Rule(2, "PROHIBITED_FINAL", "禁售且不可申诉", ("not eligible for appeal",)),
    Rule(3, "RECALL", "CPSC 召回/安全警告", ("cpsc recall", "safety warning")),
    Rule(4, "FLAGGED", "沃尔玛内部标记(不给理由)",
         ("flagged by our internal team",)),
    Rule(5, "IP", "知识产权", ("intellectual property", "copyright"),
         pattern=re.compile(r"\bip\b\s+(?:policy|claim|related)")),
    # 序 6:⚠ 后两串是 **2026-09-01 首轮生产对照补收**(旧 C 口径漏在新判据外):
    # `partnered with select brands`(生产 7 条,语料 #74)与 `biz-cn`(生产 87 条,
    # 语料 #72 —— 沃尔玛只给一个工单代码,正文里没有 brand 字样)。
    # biz-cn 行在处置层单独标 biz_cn 维度、只拉 ASIN 不拉品牌(第二步细化)。
    Rule(6, "BRAND", "品牌未授权",
         ("brand restrictions", "not authorized to list this brand",
          "partnered with select brands", "biz-cn")),
    # 序 7:资质门优先于政策(判例定稿:Jewelry…Covered Goods 与 Textiles
    # 那两条正文都是"要预审批/限特定卖家",病根是没资质不是商品违禁)。
    # ⚠ requires? —— 生产原文两种人称都有:"category that **requires**
    # pre-approval" 与 "these categories **require** pre-approval"(语料 #32)。
    Rule(7, "GATED", "类目需预审批/资质",
         ("restricted to certain sellers", "request approval to sell",
          "enhanced vetting program", "health & compliance page"),
         pattern=re.compile(r"requires?\s+pre-approval")),
    Rule(8, "PRICE", "价格规则", ("pricing rule", "price gouging",
                                  "unintended price")),
    # 序 9:内容问题。⚠ **不许用裸 `content standards`** —— 政策正文里有
    # "do not meet **offensive** content standards"(sex toys 那条,语料 #34),
    # 裸串会把政策拒误抢成内容问题。判据必须带主语("our"/"quality")。
    # 后四串是 **2026-09-01 首轮生产对照补收**(旧 I 口径漏在新判据外):
    # `content policy`(生产 200 条,语料 #71)/ 主图缺失两串(11 条,语料 #73)/
    # `authenticity claims`(5 条,语料 #75)。
    # ⚠ `content policy` 与序 15 的政策词根隔着六个表序,靠的是"连续子串":
    # 政策原文一律是 "…Offensive Content." / "…Offensive Content, Halloween
    # Items." 后另起一句 "Walmart's policy prohibits…",Content 与 policy 之间
    # 永远隔着句号/逗号,拼不出 `content policy`(语料 #14/#21/#34/#44 + feed
    # #13 逐条验过)。**别把这串放宽成 `content` + `polic` 的松匹配。**
    Rule(9, "CONTENT", "内容/图片不合标准",
         ("content issues", "does not meet our content standards",
          "content quality standards", "image guidelines", "placeholder images",
          "content policy", "missing a primary image", "main image url",
          "authenticity claims")),
    Rule(10, "SPECIAL", "特殊计划(Resold/Preorder/Pre-owned/Restored)",
         ("resold program", "preorder program", "pre-owned", "restored program")),
    # 序 11:⚠ `tax code` 是 **2026-09-01 首轮生产对照补收**(旧 H 口径,生产
    # 4 条,语料 #76:"Tax code information was not added during item setup")。
    Rule(11, "INFO", "信息缺失",
         ("no price was found", "shipping information was not added",
          "active distribution center", "missing required logistics",
          "tax code")),
    Rule(12, "SYSTEM", "沃尔玛系统错误", ("internal error occurred", "glitch")),
    Rule(13, "STAGE", "Stage 未上线(中性)", ("stage status until you go live",)),
    Rule(14, "EXPIRED", "End Date 过期", ("end date has passed",)),
    # 序 15:通用政策拒。覆盖 Products/Product 两形与缺首字母 typo。
    Rule(15, "POLICY", "违反禁售政策(通用)",
         all_of=("prohibited product", "policy")),
    # 序 16:显式杂项清单 —— 计入 unlisted,**不进 unknown 告警**(已知就这三种)。
    # `currently under review` 是 **2026-09-01 首轮生产对照补收**(生产 2 条,
    # 语料 #77):审查中是**自愈态**(24 小时内自动复架),不造码、也不该进
    # unknown 告警把人叫起来。
    Rule(16, "OTHER", "显式杂项(business decision / trust & safety / 审查中)",
         ("business decision", "trust & safety", "currently under review")),
    # 序 17:兜底 —— **必进 unknown 告警清单,原文全文保留**。
    Rule(17, "OTHER", "未识别(兜底)", catch_all=True),
)

_RULE_UNKNOWN = RULES[-1]
_RULE_UNLISTED = RULES[-2]
# feed 政策族只过序 1-15(方案 §3.6 通道 2):序 0 是 AI 通道自己的事,
# 序 16/17 的 OTHER 不在政策族的语义里。
_POLICY_CHANNEL_RULES = tuple(r for r in RULES if 1 <= r.order <= 15)


def _hit(rule: Rule, fold: str) -> bool:
    if rule.catch_all:
        return True
    if rule.all_of and all(n in fold for n in rule.all_of):
        return True
    if any(n in fold for n in rule.needles):
        return True
    return bool(rule.pattern and rule.pattern.search(fold))


def _first_hit(fold: str, rules: Iterable[Rule]) -> Rule | None:
    for rule in rules:
        if _hit(rule, fold):
            return rule
    return None


# ══════════════════════════════════════════════════════════════════════════════
#  三、政策名抽取(方案 §3.4;与码正交,对每个原子独立跑)
# ══════════════════════════════════════════════════════════════════════════════

# **冒号必需**:无冒号 = 无候选,不猜。生产两个反例钉死了这条:
#   · `*Prohibited Product Policy* for Toys`      —— 类别在标记外
#   · `Children's Products Prohibited Products Policy` —— 结构反置
# 候选字符集排除 . ; | @ *:句号/分号断句,`*…*`(feed 侧星号包裹)与残留
# 标记自然成为右边界。候选长度上限 160:官方最长政策名 89 字符(`Jewelry, …
# Precious Metals (Covered Goods)`),旧上限 80 把它截成 `…(Cover`,2026-09-02
# 真跑改名后的首份报告里 14 条因此 join 不上政策表。
_POLICY_RE = re.compile(
    r"Prohibited\s+Products?\s+Polic(?:y|ies)\s*:\s*([^.;|@*]{2,160})")

# 候选两端要剥的标点(残缺标记会留下 `)`、feed 侧会留下 `*`)
_TRIM = " \t\r\n.,;:!?([]{}<>\"'`*|-–—_/\\"   # 无 `)`:配对尾括号要留,见 _strip_edges
# 前置停用词(方案 §3.4.2)
_STOPWORDS = frozenset({"walmart", "walmart's", "our", "the", "this"})
# 已知子类词形家族(方案 §3.4.3):逗号后文本命中即收进 policy_sub。
# `politics` 是 2026-09-01 轮次二补的家族成员(方案 §3.4.3 更新);语料里没有
# Politics 全文,单元测试用拟造串钉行为(标 synthetic,不进 fixtures)。
_SUB_FAMILY = ("halloween", "inappropriate", "intolerance", "violence",
               "sex toy", "politics")
# 逗号后的连接词:政策名自己带的逗号(Tobacco, E-Cigarettes, **and** Vaping…)
_JOINERS = frozenset({"and", "or", "&"})


class PolicyName(NamedTuple):
    """政策名抽取结果:name=主名(抽不出给 None),sub=子类名(无则 None)。"""

    name: str | None
    sub: str | None


def _norm_key(name: str | None) -> str:
    """输入:政策名 → 输出:比对键(= `services/policy_names.norm_category`)。

    ⚠ **不是第二份归一化**(2026-09-02 归并):这里对的是"沃尔玛报错正文里抠出来
    的候选串 ↔ 政策表",`policy_names` 对的是"官方转录件标题 ↔ 政策表" —— 两个
    调用面,同一个问题("这两个政策名是不是同一个"),所以只留一份实现(仓规:
    每个能力只有一条实现路径)。归并前这里只做折叠空白 + casefold + 弯引号归直,
    于是报错正文里的 `Plants & Seeds` / 牛津逗号 Tobacco / 不带 `(Covered Goods)`
    的 Jewelry 三种写法**改名后照样 join 不上**(白白进"政策表缺口"清单);
    `norm_category` 的 `&`↔`and`、去逗号、削括号后缀、单复数四条正好补上。

    放宽的代价评估过:归一化合错两个名字,在 `policy_sync` 那边是**覆盖正文**,
    在这里只是报告侧 join 多认一条(`policy_join` **不参与任何判定**,
    `policy_name` 一律保留原文)。而 42 个官方名两两归一化不碰撞由测试钉死,
    合错的前提本就不成立。
    """
    return norm_category(name)


# 停用词也过同一把尺子:`_norm_key` 会把 `this` 削成 `thi`、`Walmart's` 削成
# `walmart`,拿原词去比就会**悄悄漏掉**(前缀词不再被剥,候选串多带一个词)。
_STOPWORD_KEYS = frozenset(_norm_key(w) for w in _STOPWORDS)


def _strip_edges(cand: str) -> str:
    """输入:候选串 → 输出:两端剥标点,**配对的尾 `)` 保留**,孤 `)` 照剥。

    残缺标记会留下孤 `)`(要剥);可官方名自己带括号后缀 —— `…Precious Metals
    (Covered Goods)` —— 一律剥就成了 `…(Covered Goods`,`norm_category` 的括号
    后缀削不掉,join 不上(2026-09-02 真跑改名后首份报告的 14 条,与正则 80 字
    上限是同一批)。判据:右括号比左括号多才是孤的。
    """
    s = cand.strip(_TRIM)
    while s.endswith(")") and s.count(")") > s.count("("):
        s = s[:-1].rstrip(_TRIM)
    return s


def _strip_stopwords(cand: str) -> str:
    while cand:
        head, _, rest = cand.partition(" ")
        if _norm_key(head).strip(_TRIM) in _STOPWORD_KEYS and rest.strip():
            cand = rest.strip()
            continue
        return cand
    return cand


def _split_main_sub(cand: str) -> PolicyName:
    """输入:清洗过的候选 → 输出:(主名, 子类名)。

    ⚠ 与方案 §3.4 步 2/3 的偏差(已记入交付报告):方案原文是"逗号一律截断,
    子类词形除外";但生产政策名**自己就带逗号** —— `Tobacco, E-Cigarettes,
    and Vaping Products`(语料 #45)与 `Jewelry, Watches, Precious Gemstones,
    Currency, Coins and Precious Metals`(语料 #32),无条件截断会把它们腰斩成
    "Tobacco" / "Jewelry"。故逗号截断只在逗号后是**续句**(小写起头且首词不是
    and/or 连接词)时生效 —— 那正是方案要防的 "Policy: X, please review…"。
    """
    if "," not in cand:
        return PolicyName(cand or None, None)
    head, tail = (_strip_edges(p) for p in cand.split(",", 1))
    if head and any(k in tail.casefold() for k in _SUB_FAMILY):
        return PolicyName(head, tail or None)
    out, pos = cand, 0
    while (i := out.find(",", pos)) >= 0:
        rest = out[i + 1:].lstrip()
        first = rest.split(" ", 1)[0].casefold().strip(_TRIM)
        if rest[:1].islower() and first not in _JOINERS:
            out = out[:i]
            break
        pos = i + 1
    out = _strip_edges(out)
    return PolicyName(out or None, None)


def extract_policy(atom_raw: str | None) -> PolicyName:
    """输入:一条原子原文 → 输出:PolicyName(政策名, 子类名);抽不出给 (None, None)。

    与码正交:通用政策拒抽不出类别名是**常态**(生产 3,363 条),
    `name=None` 合法、不告警。抽出候选但与政策表 join 不上的,由调用方用
    `policy_join()` 判并进"政策表缺口"清单(报告显示,不算 unknown)。
    """
    m = _POLICY_RE.search(normalize_atom(atom_raw).text)
    if not m:
        return PolicyName(None, None)
    cand = _strip_stopwords(_strip_edges(m.group(1)))
    if len(cand) < 2:
        return PolicyName(None, None)
    return _split_main_sub(cand)


# ── 政策表 join(报告侧消费;**不参与判定**,policy_name 一律保留原文)──────
#
# ⚠ **别名表 `POLICY_ALIASES` / `alias_gaps` 已于 2026-09-03 C 批退役**
#   (连同 `registry.resources.POLICY_LEGACY_NAMES` 与 `policy_names.to_official`)。
#   它是改名过渡期的桥:报错正文里的政策名一直是**官方全称**,而政策表存量行
#   用的是旧仓搬迁时的缩写名,两边对不上会把一堆真实存在的政策算成"政策表缺口"。
#   2026-09-02 `policy_sync` 真跑把表内名全部改成官方拼写之后,**直接键就命中**,
#   这座桥的两头连的是同一个地方 —— 留着 = 一份永远不会再被验证的历史映射。
#   今后报错正文里出现表里没有的政策名,它就该进「政策表缺口」清单让人看见
#   (那正是这张表原本明令禁止用来做语义合并的那一类)。
def policy_join(candidate: str | None,
                policy_names: Iterable[str] | None) -> str | None:
    """输入:政策名候选 + 政策表 category_en 集合 → 输出:命中的 category_en(不中给 None)。

    只走词形归一(`policy_names.norm_category`)—— 缩写差这类**语义合并**不做:
    对不上就是对不上,进「政策表缺口」清单等人裁决。

    ⚠ 表按**名字序**构造:入参常是 set,而归一化后两行撞同一个键时"谁赢"由
    迭代序决定 —— 不定序会让同一份报错语料在两次进程里 join 到不同的行,
    而那种漂移不会报错(政策表是反推表,只差大小写/词形的两行不该有但可能有)。
    """
    if not candidate or not policy_names:
        return None
    table = {_norm_key(n): n for n in sorted(policy_names) if n}
    return table.get(_norm_key(candidate))


# ══════════════════════════════════════════════════════════════════════════════
#  四、归类(方案 §3.5 / §3.6)
# ══════════════════════════════════════════════════════════════════════════════


class AtomResult(NamedTuple):
    """单原子归类结果。atom 保留**传进来的原文**(unknown 清单要全文,不要洗过的)。"""

    code: str
    policy_name: str | None
    policy_sub: str | None
    via_ai: bool
    rule_order: int
    unlisted_term: str | None       # 序 16 显式清单命中的那个词条
    atom: str


class Result(NamedTuple):
    """记录级归类结果(字段与方案 §3.5 逐字一致)。"""

    code: str
    name: str
    policy_name: str | None
    policy_sub: str | None
    via_ai: bool
    atom_codes: tuple[tuple[str, str | None], ...]
    unknown: tuple[str, ...]
    unlisted: tuple[tuple[str, int], ...]


class FeedResult(NamedTuple):
    """feed 报错归类结果。err_code/field 原样带回(operational 通道靠它们说话)。"""

    channel: str                    # content_ai / policy / async / operational
    code: str | None                # 16 码之一;async/operational 不强行进码表
    policy_name: str | None
    policy_sub: str | None
    via_ai: bool
    err_code: str | None
    field: str | None


def _classify(atom: str | None, rules: Iterable[Rule]) -> AtomResult:
    norm = normalize_atom(atom)
    rule = _first_hit(norm.fold, rules) or _RULE_UNKNOWN
    name, sub = extract_policy(atom)
    term = None
    if rule is _RULE_UNLISTED:
        term = next((n for n in rule.needles if n in norm.fold), None)
    return AtomResult(rule.code, name, sub, rule.via_ai, rule.order, term,
                      atom or "")


def classify_atom(atom: str | None) -> AtomResult:
    """输入:一条原子原文 → 输出:AtomResult(码 + 政策名 + AI 标记 + 命中序)。

    表序即优先级,首命中即码(方案 §3.3);序 0 命中即短路,正文不再进任何规则。
    """
    return _classify(atom, RULES)


def classify_reasons(atoms: Iterable[str] | None,
                     policy_names: Iterable[str] | None = None) -> Result:
    """输入:原子列表(+ 可选政策表集合)→ 输出:记录级 Result。

    主码 = 各原子码按 `ERROR_CATEGORY_SEVERITY` 取名次最小者(终局优先,
    非中性永远压过中性);记录级 policy_name/policy_sub 取**赢下主码那个原子**的
    (其余原子的政策名在 atom_codes 里逐条留着)。

    ⚠ `unknown` 引擎不吞:落 OTHER(未识别) 的原子原文全部带回,调用方必须告警。
    `policy_names` 只为 join 校验预留(见 policy_join),**不改判定、也不改
    policy_name 取值** —— 语料钉死抽出什么保留什么(`Auto and Motor Vehicles`
    不许被别名改写成 `Auto & Motor Vehicles`)。
    """
    results = [_classify(a, RULES) for a in (atoms or []) if (a or "").strip()]
    if not results:
        return Result("OTHER", resources.ERROR_CATEGORY_CODES["OTHER"],
                      None, None, False, (), (), ())
    win = min(results, key=lambda r: _SEVERITY_RANK[r.code])
    unlisted: dict[str, int] = {}
    for r in results:
        if r.unlisted_term:
            unlisted[r.unlisted_term] = unlisted.get(r.unlisted_term, 0) + 1
    return Result(
        code=win.code,
        name=resources.ERROR_CATEGORY_CODES[win.code],
        policy_name=win.policy_name,
        policy_sub=win.policy_sub,
        via_ai=any(r.via_ai for r in results),
        atom_codes=tuple((r.code, r.policy_name) for r in results),
        unknown=tuple(r.atom for r in results
                      if r.rule_order == _RULE_UNKNOWN.order),
        unlisted=tuple(sorted(unlisted.items())),
    )


def classify_feed_error(code: str | None, field: str | None,
                        description: str | None,
                        status: str | None) -> FeedResult:
    """输入:feed 报错四元组 → 输出:FeedResult(通道 + 码 + 政策名)。

    通道次序照方案 §3.6:
      1 code ∈ WALMART_ERR_CONTENT 或正文含 AI 尾句 → content_ai
        (**code 锚必须保留**:生产明细的 description 常被截断,AI 尾句可能不在截断内)
      2 field ∈ WALMART_ERR_FIELD_POLICY 且 status=='failed' → policy(正文过序 1-15)
      3 code ∈ WALMART_ERR_ASYNC_REVIEW → async(审查中,不是报错)
      4 其余 → operational,原样带回 (code, field);已结构化,不强行进 16 码表

    ⚠ `status=='failed'` 这道闸是硬的:生产契约里 SUCCESS 回执可以同时带
    ingestionErrors(带警告的成功),field 锚不许把它们判成政策拒。
    本步只被对照报告消费,**不接 listing_sheet.classify_receipt**。
    """
    fold = normalize_atom(description).fold
    if (code and code in resources.WALMART_ERR_CONTENT) or _AI_TAIL in fold:
        return FeedResult("content_ai", "CONTENT", None, None, True, code, field)
    if (field in resources.WALMART_ERR_FIELD_POLICY
            and (status or "").strip().casefold() == "failed"):
        atom = _classify(description, _POLICY_CHANNEL_RULES)
        return FeedResult("policy", atom.code, atom.policy_name, atom.policy_sub,
                          False, code, field)
    if code and code in resources.WALMART_ERR_ASYNC_REVIEW:
        return FeedResult("async", None, None, None, False, code, field)
    return FeedResult("operational", None, None, None, False, code, field)
